var annotated_dup =
[
    [ "bin_series", "classbin__series.html", "classbin__series" ],
    [ "cos_series", "classcos__series.html", "classcos__series" ],
    [ "cosh_series", "classcosh__series.html", "classcosh__series" ],
    [ "epsilon_algorithm", "classepsilon__algorithm.html", "classepsilon__algorithm" ],
    [ "erf_series", "classerf__series.html", "classerf__series" ],
    [ "exp_series", "classexp__series.html", "classexp__series" ],
    [ "exp_squared_erf_series", "classexp__squared__erf__series.html", "classexp__squared__erf__series" ],
    [ "four_arctan_series", "classfour__arctan__series.html", "classfour__arctan__series" ],
    [ "half_asin_two_x_series", "classhalf__asin__two__x__series.html", "classhalf__asin__two__x__series" ],
    [ "inverse_1mx_series", "classinverse__1mx__series.html", "classinverse__1mx__series" ],
    [ "inverse_sqrt_1m4x_series", "classinverse__sqrt__1m4x__series.html", "classinverse__sqrt__1m4x__series" ],
    [ "ln1mx_series", "classln1mx__series.html", "classln1mx__series" ],
    [ "m_fact_1mx_mp1_inverse_series", "classm__fact__1mx__mp1__inverse__series.html", "classm__fact__1mx__mp1__inverse__series" ],
    [ "mean_sinh_sin_series", "classmean__sinh__sin__series.html", "classmean__sinh__sin__series" ],
    [ "series_acceleration", "classseries__acceleration.html", "classseries__acceleration" ],
    [ "series_base", "classseries__base.html", "classseries__base" ],
    [ "shanks_transform", "classshanks__transform.html", "classshanks__transform" ],
    [ "shanks_transform_alternating", "classshanks__transform__alternating.html", "classshanks__transform__alternating" ],
    [ "sin_series", "classsin__series.html", "classsin__series" ],
    [ "sinh_series", "classsinh__series.html", "classsinh__series" ],
    [ "x_1mx_squared_series", "classx__1mx__squared__series.html", "classx__1mx__squared__series" ],
    [ "xmb_Jb_two_series", "classxmb__Jb__two__series.html", "classxmb__Jb__two__series" ]
];