var series_8h =
[
    [ "series_base", "classseries__base.html", "classseries__base" ],
    [ "exp_series", "classexp__series.html", "classexp__series" ],
    [ "cos_series", "classcos__series.html", "classcos__series" ],
    [ "sin_series", "classsin__series.html", "classsin__series" ],
    [ "cosh_series", "classcosh__series.html", "classcosh__series" ],
    [ "sinh_series", "classsinh__series.html", "classsinh__series" ],
    [ "bin_series", "classbin__series.html", "classbin__series" ],
    [ "four_arctan_series", "classfour__arctan__series.html", "classfour__arctan__series" ],
    [ "ln1mx_series", "classln1mx__series.html", "classln1mx__series" ],
    [ "mean_sinh_sin_series", "classmean__sinh__sin__series.html", "classmean__sinh__sin__series" ],
    [ "exp_squared_erf_series", "classexp__squared__erf__series.html", "classexp__squared__erf__series" ],
    [ "xmb_Jb_two_series", "classxmb__Jb__two__series.html", "classxmb__Jb__two__series" ],
    [ "half_asin_two_x_series", "classhalf__asin__two__x__series.html", "classhalf__asin__two__x__series" ],
    [ "inverse_1mx_series", "classinverse__1mx__series.html", "classinverse__1mx__series" ],
    [ "x_1mx_squared_series", "classx__1mx__squared__series.html", "classx__1mx__squared__series" ],
    [ "erf_series", "classerf__series.html", "classerf__series" ],
    [ "m_fact_1mx_mp1_inverse_series", "classm__fact__1mx__mp1__inverse__series.html", "classm__fact__1mx__mp1__inverse__series" ],
    [ "inverse_sqrt_1m4x_series", "classinverse__sqrt__1m4x__series.html", "classinverse__sqrt__1m4x__series" ],
    [ "one_twelfth_3x2_pi2_series", "classone__twelfth__3x2__pi2__series.html", "classone__twelfth__3x2__pi2__series" ],
    [ "x_twelfth_x2_pi2_series", "classx__twelfth__x2__pi2__series.html", "classx__twelfth__x2__pi2__series" ],
    [ "ln2_series", "classln2__series.html", "classln2__series" ],
    [ "one_series", "classone__series.html", "classone__series" ],
    [ "minus_one_quarter_series", "classminus__one__quarter__series.html", "classminus__one__quarter__series" ],
    [ "pi_3_series", "classpi__3__series.html", "classpi__3__series" ],
    [ "pi_4_series", "classpi__4__series.html", "classpi__4__series" ],
    [ "pi_squared_6_minus_one_series", "classpi__squared__6__minus__one__series.html", "classpi__squared__6__minus__one__series" ],
    [ "three_minus_pi_series", "classthree__minus__pi__series.html", "classthree__minus__pi__series" ],
    [ "one_twelfth_series", "classone__twelfth__series.html", "classone__twelfth__series" ],
    [ "eighth_pi_m_one_third_series", "classeighth__pi__m__one__third__series.html", "classeighth__pi__m__one__third__series" ],
    [ "one_third_pi_squared_m_nine_series", "classone__third__pi__squared__m__nine__series.html", "classone__third__pi__squared__m__nine__series" ],
    [ "four_ln2_m_3_series", "classfour__ln2__m__3__series.html", "classfour__ln2__m__3__series" ],
    [ "exp_m_cos_x_sinsin_x_series", "classexp__m__cos__x__sinsin__x__series.html", "classexp__m__cos__x__sinsin__x__series" ],
    [ "NO_SERIES_EXPRESSION_GIVEN", "series_8h.html#a4e39687831ca335e062cb165b0f12c96", null ],
    [ "NO_X_GIVEN", "series_8h.html#abae30b0b2a6e7d520403e0cc8f02d4ce", null ]
];